# data config
train_dir: "/home/yiyonghao/IGARSS/dataset/mtarsi20/train"
test_dir: "/home/yiyonghao/IGARSS/dataset/mtarsi20/test"
num_class: 20

# model config
batch_size: 16
learning_rate: 0.001
momentum: 0.9
weight_decay: 5e-4
num_epoch: 100
resize_size: 448
crop_size: 448
